
import QueryProvider from "@/lib/queryClient"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  

  return (
    <html lang="en">
        <body>
          <QueryProvider>
            {children}
          </QueryProvider>
        </body>
    </html>
  )
}
